
Trainee_Name: 'Martin Yeo'
Skills_By_Date:
  - date    : 2019-04-08
    Skills  :
      'Skill 1' : 2
      'Skill 2' : 5
      'Skill 3' : 1
      'Skill 4' : 1
      'Skill 5' : 3

  - date    : 2019-04-12
    Skills  :
      'Skill 1' : 3
      'Skill 2' : 5
      'Skill 3' : 2
      'Skill 4' : 2
      'Skill 5' : 4
      'Skill 6' : 1