
Chart Title : 'Martin Yeo Python Skill Progression'
Chart Size  :
  Width   : 4
  Height  : 4
Skills_By_Date:
  - Date      : 2019-04-08
    Color Hex : '#00FF00'
    Skills    :
      'Skill 1' : 2
      'Skill 2' : 5
      'Skill 3' : 1
      'Skill 4' : 1
      'Skill 5' : 3

  - Date      : 2019-04-12
    Color Hex2 : '#00FFFF'
    Skills    :
      'Skill 1' : 3
      'Skill 2' : 5
      'Skill 3' : 2
      'Skill 4' : 2
      'Skill 5' : 4
      'Skill 6' : 1