
Chart Title : Martin Yeo Python Skill Progression
Chart Size  :
  Width   : 6
  Height  : 6
Skills By Date:
  - Date      : 2019-04-08
    Colour    : blue
    Skills    :
      Skill 1 : 2
      Skill 2 : 5
      Skill 3 : 1
      Skill 4 : 1
      Skill 5 : 3

  - Date      : 2019-04-12
    Colour    : red
    Skills    :
      Skill 1 : 3
      Skill 2 : 5
      Skill 3 : 2
      Skill 4 : 3.5
      Skill 5 : 4
      Skill 6 : 1