Chart Title : Martin Yeo Python Skill Progression
Chart Size  :
  Width   : 6
  Height  : 6
Competencies By Date:
  - Date      : 2019-04-08
    Skills    :
      Skill 1 : 2
      Skill 2 : 5
      Skill 3 : 1
      Skill 4 : 1
      Skill 5 : 3
  - Date      : 2019-05-08
    Skills    :
      Skill 1 : 3
      Skill 2 : 5
      Skill 3 : 2
      Skill 4 : 2
      Skill 5 : 4